---
title: "CLIMEX_CL_Annual_extract"
author: "Anna Szyniszewska"
date: "2023-06-28"
output: html_document
---

```{r message=FALSE, warning=FALSE, echo=FALSE, results="hide"}
# Load required libraries
library(raster)
library(ncdf4)
library(sf)
library(tmap)
library(rmapshaper)

```

```{r message=FALSE, warning=FALSE, echo=FALSE, results="hide"}
path <- "C:/CLIMEX/"
setwd(path)

# B dorsalis files
file1 = "B. dorsalis/Bd_CLResults_CM30_1995H_V2_ParamFFIPM_NoIrr_Annual.nc"
file2 = "B. dorsalis/Bd_CLResults_CM30_1995H_V2_ParamFFIPM_Irr_Annual.nc"

# B zonata files
# file1 = "B. zonata/Bz_CLResults_CM30_1995H_V2_ParamFFIPM_NoIrr_Annual.nc"
# file2 = "B. zonata/Bz_CLResults_CM30_1995H_V2_ParamFFIPM_Irr_Annual.nc"

# C capitata files
# file1 = "C. capitata/Cc_CLResults_CM30_1995H_V2_ParamFFIPM_NoIrr_Annual.nc"
# file2 = "C. capitata/Cc_CLResults_CM30_1995H_V2_ParamFFIPM_Irr_Annual.nc"


mask = "CM30_1995H_V2_gmia_v5_aei_h_classified10ha.tif"

# Variable of interest names: (could explore more such as MI, TI, CS etc)
dname <- c("EI","GI")
# Define which dname will be used:
k <- 1

Irr.r <- raster("C:/CLIMEX/CM30_1995H_V2_gmia_v5_aei_h_classified10ha.tif")

# Load netcdf files
clim_ncdf <- nc_open(paste0("C:/CLIMEX/",file1))
clim_ncdf2 <- nc_open(paste0("C:/CLIMEX/",file2))
```


```{r message=FALSE, warning=FALSE, echo=FALSE, results="hide"}
# fix lat and lon
get_nc <- function(ncdf,dname){
  lon <- seq(from = -179.75, to = 179.75, by = 0.5) 
  # nlon <- dim(lon)
  # head(lon)
  lat <- seq(from = -89.75, to = 83.75, by = 0.5) 
  r1 <- ncvar_get(ncdf,dname)
  rotate <- function(x) t(apply(x, 2, rev))
  r <- rotate(rotate(rotate(r1)))
  
  vec <- c(339:348)
  # New matrix 'new_r' with all 2, 
  new_r <- matrix(0,nrow=length(lat),ncol=length(lon))  
  # 'new_r' rows getting filled with `r` values
  new_r[-vec,] <- r  
  #Create extent for the raster image
  e <- raster::extent(min(lon) - 0.25, max(lon) + 0.25,
                      min(lat) - 0.25, max(lat) + 0.25)

  r_final <- raster::raster(nrow = length(lat), ncol = length(lon),
                      ext = e, crs = "+proj=longlat +datum=WGS84 +no_defs")
  # And assign new_r to the RasterLayer
  raster::values(r_final) <- new_r
  
  return(r_final)
}

r_NoIrr <- get_nc(clim_ncdf,dname[k])
r_Irr <- get_nc(clim_ncdf2,dname[k])

## Create a composite raster:

# Crop irrigation layer: 
Irr.r.c <- crop(x = Irr.r, y = r_Irr)
#plot(Irr.r.c)

composite.fun <- function(Irr, Ri, Rn){
  Irr2 <- Irr+1
  Irr2 <- reclassify(Irr2, cbind(2, 0))
  Final <- Ri*Irr+Rn*Irr2
  return(Final)
}

### Create a composite map
r_composite <- composite.fun(Irr.r.c, r_Irr, r_NoIrr)

plot(r_composite)

```
```{r}

#######################
# Futher part of the code was used for mapping, might need transformation
##########################


```

```{r message=FALSE, warning=FALSE, echo=FALSE}
# use tmap
plot(r_composite)
#raster::writeRaster(r_composite, "r_composite.tif")
```

```{r message=FALSE, warning=FALSE, echo=FALSE, results="hide"}
# read distribution points for capitata
status_ok <- st_read("CLIMEX results/capitata_status_ok.geojson")
#plot(cc_status_ok)
status_ok <- st_read("CLIMEX results/dorsalis_status_ok.geojson")

status_ok <- st_read("CLIMEX results/zonata_status_ok.geojson")
```


```{r message=FALSE, warning=FALSE, echo=FALSE, results="hide"}
#read countries shape
World <- rnaturalearth::ne_countries(scale = 10, continent = NULL, returnclass = "sf", type = "countries")
World <- rmapshaper::ms_simplify(World, keep = 0.1, keep_shapes = TRUE)
#st_write(World, "CLIMEX results/world.geojson")
```

```{r message=FALSE, warning=FALSE, echo=FALSE, results="hide"}
box <- c(-169, -55, 194, 78)
box_sp <- as(extent(box[1],box[3],box[2],box[4]), 'SpatialPolygons')
crs(box_sp) <- "+proj=longlat +datum=WGS84 +no_defs"

max(values(r_composite), na.rm = T)
#crop raster
r_composite_cropped = crop(r_composite, box_sp)
plot(r_composite_cropped)
r_Irr_cropped = crop(r_Irr, box_sp)

r_NoIrr_cropped = crop(r_NoIrr, box_sp) 

#crop polygon
World_without_antarctica <- World %>% dplyr::filter(sovereignt != "Antarctica")
#plot(World_without_antarctica)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}

cuts_mean=c(0,seq(1,100,1)) # EI
cuts_l_mean <- length(cuts_mean)
cols_brown_yellow_mean <- c("grey", colorRampPalette(c("lightyellow","yellow","orange","red" ,"red3"))(cuts_l_mean-1))

```

```{r message=FALSE, warning=FALSE, echo=FALSE}

map_robin <- tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_fill(col = "grey") +
    tm_shape(r_composite_cropped, raster.warp = FALSE, projection="+proj=robin") +
    tm_raster(style = 'cont', palette =  cols_brown_yellow_mean,
              legend.show = TRUE, title = "EI", breaks = c(seq(0,100,5)), alpha = 0.8) +
    tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_borders(lwd = 1, col = "grey60") +
    tm_symbols(size = 0.06, 
               shape = 21, 
               border.lwd = 0.7, 
               border.col = "black",
               border.alpha = 0.8,
               col = "white",
               alpha = 0.2) + 
    tm_layout(main.title.position = "left",
              main.title.size = 0.9, 
              earth.boundary = FALSE,
              bg.color = "white",
              space.color="white",
              legend.format = list(fun = function(x) {
                ifelse(x %in% c(0, 10, 20, 30, 40, 50 ,60 ,70 ,80, 90, 100), x, "")
                }),
              legend.title.size=1,                   #0.9 or  0.8 for small maps
              legend.text.size = 0.8, 
              fontface="bold",#0.6 or 0.7
              frame = FALSE) +
    tm_legend(position = c("left", "bottom"))


tmap_save(map_robin, "CLIMEX results/bz_composite_map_robin.png")
#tmaptools::palette_explorer()
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
#leaflet map

library(leaflet)

pal <- colorNumeric(c("grey","lightyellow","yellow","orange","red" ,"red3"), c(0,seq(1,100,1)),
  na.color = "transparent")

leaflet() %>% addTiles() %>%
  addRasterImage(r_composite_cropped, colors = cols_brown_yellow_mean, opacity = 0.8) 

```

```{r message=FALSE, warning=FALSE, echo=FALSE}

map_robin <- tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_fill(col = "grey") +
    tm_shape(r_Irr_cropped, raster.warp = FALSE, projection="+proj=robin") +
    tm_raster(style = 'cont', palette =  cols_brown_yellow_mean,
              legend.show = TRUE, title = "EI", breaks = c(seq(0,100,5)), alpha = 0.8) +
    tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_borders(lwd = 1, col = "grey60") +
    tm_layout(main.title = "Irrigated scenario",
              main.title.position = "left",
              main.title.size = 0.9, 
              earth.boundary = FALSE,
              bg.color = "white",
              space.color="white",
              legend.format = list(fun = function(x) {
                ifelse(x %in% c(0, 10, 20, 30, 40, 50 ,60 ,70 ,80, 90, 100), x, "")
                }),
              legend.title.size=1,                   #0.9 or  0.8 for small maps
              legend.text.size = 0.8, 
              fontface="bold",#0.6 or 0.7
              frame = FALSE) +
    tm_legend(position = c("left", "bottom"))


tmap_save(map_robin, "CLIMEX results/ei_bd_r_Irr.png")
 
```

```{r message=FALSE, warning=FALSE, echo=FALSE}

map_robin <- tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_fill(col = "grey") +
    tm_shape(r_NoIrr_cropped, raster.warp = FALSE, projection="+proj=robin") +
    tm_raster(style = 'cont', palette =  cols_brown_yellow_mean,
              legend.show = TRUE, title = "EI", breaks = c(seq(0,100,5)), alpha = 0.8) +
    tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_borders(lwd = 1, col = "grey60") +
    tm_layout(main.title = "Rainfed scenario",
              main.title.position = "left",
              main.title.size = 0.9, 
              earth.boundary = FALSE,
              bg.color = "white",
              space.color="white",
              legend.format = list(fun = function(x) {
                ifelse(x %in% c(0, 10, 20, 30, 40, 50 ,60 ,70 ,80, 90, 100), x, "")
                }),
              legend.title.size=1,                   #0.9 or  0.8 for small maps
              legend.text.size = 0.8, 
              fontface="bold",#0.6 or 0.7
              frame = FALSE) +
    tm_legend(position = c("left", "bottom"))


tmap_save(map_robin, "CLIMEX results/ei_bd_r_NoIrr.png")
 
```

```{r message=FALSE, warning=FALSE, echo=FALSE}

map_robin <- tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_fill(col = "grey") +
    tm_shape(r_composite_cropped, raster.warp = FALSE, projection="+proj=robin") +
    tm_raster(style = 'cont', palette =  cols_brown_yellow_mean,
              legend.show = TRUE, title = "EI", breaks = c(seq(0,100,5)), alpha = 0.8) +
    tm_shape(st_geometry(World_without_antarctica), projection="+proj=robin") +
    tm_borders(lwd = 1, col = "grey60") +
    tm_layout(main.title = "Composite scenario",
              main.title.position = "left",
              main.title.size = 0.9, 
              earth.boundary = FALSE,
              bg.color = "white",
              space.color="white",
              legend.format = list(fun = function(x) {
                ifelse(x %in% c(0, 10, 20, 30, 40, 50 ,60 ,70 ,80, 90, 100), x, "")
                }),
              legend.title.size=1,                   #0.9 or  0.8 for small maps
              legend.text.size = 0.8, 
              fontface="bold",#0.6 or 0.7
              frame = FALSE) +
    tm_legend(position = c("left", "bottom"))


tmap_save(map_robin, "CLIMEX results/ei_bd_r_composite.png")
 
```
